Dark mode
schul-cloud/schulcloud-flutter pull request #108
Opened 2020-01-09 13:39 UTC by JonasWanke

**Fixes: #56, fixes: #81, fixes: #104**

## Theming for different instances

Individual apps are now available for:
- Schul-Cloud (sc)
- Schul-Cloud Brandenburg (brb)
- Niedersächsische Bildungscloud (n21)
- Open Schul-Cloud (open)
- Thüringer Schulcloud (thr)

`.vscode/launch.json` contains the correct start configurations for each of them.

| Schul-Cloud | Schul-Cloud Brandenburg | Niedersächsische Bildungscloud |
| :------------: | :------------: | :------------: |
| ![image](https://user-images.githubusercontent.com/19330937/72069084-ab897280-32e6-11ea-8d5c-4d74ac3eda6d.png) | ![image](https://user-images.githubusercontent.com/19330937/72069094-b512da80-32e6-11ea-8516-c06b7d5c21d4.png) | ![image](https://user-images.githubusercontent.com/19330937/72069114-c360f680-32e6-11ea-8b69-0fc3e6aa8292.png) |
| **Open Schul-Cloud** | **Thüringer Schulcloud** | **Launcher Icons** |
| ![image](https://user-images.githubusercontent.com/19330937/72069126-cd82f500-32e6-11ea-82ec-199adc1be41b.png) | ![image](https://user-images.githubusercontent.com/19330937/72069152-da074d80-32e6-11ea-9f90-0cee2ea09c4f.png) | ![image](https://user-images.githubusercontent.com/19330937/72072067-7b919d80-32ed-11ea-89ef-cd007ff2a221.png) |

## Dark mode
(based on system settings)

| ![image](https://user-images.githubusercontent.com/19330937/72069210-f7d4b280-32e6-11ea-9bca-121080e7cf36.png) | ![image](https://user-images.githubusercontent.com/19330937/72069214-facfa300-32e6-11ea-9dfc-1459f4538f40.png) | ![image](https://user-images.githubusercontent.com/19330937/72069219-fd31fd00-32e6-11ea-9d08-7d7c3c916846.png) |
| :------------: | :------------: | :------------: |
| ![image](https://user-images.githubusercontent.com/19330937/72069230-00c58400-32e7-11ea-9aab-9574af7d7fd0.png) | ![image](https://user-images.githubusercontent.com/19330937/72069234-028f4780-32e7-11ea-8da7-67c42bd993d5.png) | ![image](https://user-images.githubusercontent.com/19330937/72069238-0622ce80-32e7-11ea-8b0c-304b3274faf5.png) |
| ![image](https://user-images.githubusercontent.com/19330937/72069243-091dbf00-32e7-11ea-8ac9-357190bb050c.png) |  | |

## Miscellaneous

- update to **AndroidX**, update gradle version
- correct **privacy policy** link

2020-01-09 14:05 UTC, JonasWanke commented
(Our CI fails as widgets don't properly provide diagnostics data. This is not related to this PR and is now being tracked in #109.)

2020-01-09 15:32 UTC, janrenz commented
What happens with black logos like n21/nbc on the dark mode?

2020-01-09 16:12 UTC, janrenz commented
We also need to figure out to get this running in iOS
see https://medium.com/@animeshjain/build-flavors-in-flutter-android-and-ios-with-different-firebase-projects-per-flavor-27c5c5dac10b

2020-01-09 16:39 UTC, JonasWanke commented
@janrenz Unfortunately, I neither have any experience with developing iOS apps nor do I own any Apple-devices for testing these.

Regarding the logos: The contrast isn't always high enough for good readability on dark mode; I'll work on a fix.

2020-01-10 12:00 UTC, JonasWanke commented
Some logos (n21, open, thr) now have a variation for use on dark backgrounds. These variations were created by replacing black with white text and using a lighter shade of dark logo colors. Also, some logos on the login screen are now bigger.

2020-01-11 11:31 UTC, MarcelGarus requested changes

2020-01-11 11:31 UTC, marcelgarus commented on lib/app/theming/config.dart
> +  })  : assert(AppConfig != null),
Probably should be lowecase `appConfig`. The type always exists.

2020-01-11 11:31 UTC, marcelgarus commented on lib/news/widgets/author.dart
> +      child: Padding(
Can't we just add the padding to the surrounding `Container`?

2020-01-12 21:49 UTC, MarcelGarus approved these changes

2020-01-12 21:49 UTC, marcelgarus commented
Ready to merge!

2020-01-14 08:45 UTC, merged

2020-01-14 09:34 UTC, janrenz commented
great PR!