Redesign main UI
schul-cloud/schulcloud-flutter pull request #139
Opened 2020-01-24 22:36 UTC by marcelgarus

Using lots of colors distracted from the actual content and made the design look old. So here's a cleaner, decluttered design. :tada:

The bottom navigation bar has no menu anymore. Instead, there are several items directly inside the navigation bar, which makes navigating much easier. This is in accordance to the semi-recent design trend of removing hamburger menus in favor of more direct navigation (as seen on YouTube, Instagram, Google Maps etc.).
The account and settings information went to the (top) app bar instead, where an account avatar is displayed on the top right, just like on the web client. The app bar gets a shadow as soon as the user scrolls.

Most of the content is now organized into cards to provide a consistent layout throughout the app.
To document the chosen padding (and future design decisions), there's now a [design wiki page](https://github.com/schul-cloud/schulcloud-flutter/wiki/Design).

Also, there are now several extension methods for making coding easier.

Here are some screenshots of the new design:

dashboard | dashboard further down, elevated app bar | news
---|---|---
![image](https://user-images.githubusercontent.com/8601189/73106595-11d3df00-3efc-11ea-94cc-e979654cdaeb.png) | ![image](https://user-images.githubusercontent.com/8601189/73106610-1ac4b080-3efc-11ea-8128-3aea744dfb7a.png) | ![image](https://user-images.githubusercontent.com/8601189/73108083-a4c24880-3eff-11ea-8e6e-6fa8e61bf365.png)

courses | assignments | files
---|---|---
![image](https://user-images.githubusercontent.com/8601189/73108163-dc30f500-3eff-11ea-8d32-9d4924787076.png) | ![image](https://user-images.githubusercontent.com/8601189/73108179-e3f09980-3eff-11ea-95d5-91efc506d994.png) | ![image](https://user-images.githubusercontent.com/8601189/73108191-eeab2e80-3eff-11ea-8bce-cc6ebe60fb81.png)

account dialog | dashboard in dark mode | news in dark mode
---|---|---
![image](https://user-images.githubusercontent.com/8601189/73108231-07b3df80-3f00-11ea-9dc1-e53009204878.png) | ![image](https://user-images.githubusercontent.com/8601189/73108240-0d112a00-3f00-11ea-81cf-d1b8149a5b08.png) | ![image](https://user-images.githubusercontent.com/8601189/73108254-11d5de00-3f00-11ea-83d9-051e7501e732.png)

**Known issues**

* The course screen has the wrong title.
* The course screen has overflowing courses. This is an issue in general with the current widget and shouldn't be fixed in this PR.
* The app bar doesn't animate between screens. This is something to tackle in a future issue.
* The file browser doesn't use the new app bar yet, because it would lose the fantastic smooth transition. As soon as the new app bar supports transitions, we could migrate to the new app bar.
* The settings screen doesn't use the new app bar yet.
* The account dialog could get some better design.
* The active tab bar item is illegible in dark mode. The theme will probably be changed to fix that.
* The assignments screen isn't redesigned yet. @JonasWanke is working on that.
* The padding on the files screen is off. That's probably an issue with the `MediaQuery`'s padding and will be fixed as soon as we use a custom scaffold.
* File course items overflow, but that's an issue for another time.

2020-01-27 19:02 UTC, JonasWanke requested changes

2020-01-27 19:02 UTC, JonasWanke commented on lib/app/app.dart
> +export 'widgets/fancy_card.dart';
We might want to remove the `fancy_` prefix

2020-01-27 19:02 UTC, JonasWanke commented on lib/app/widgets/navigation_bar.dart
> +      selectedItemColor: theme.primaryColor,
This evaluates to black using the dark theme which is not distinguishable from the bar itself

2020-01-27 19:02 UTC, JonasWanke commented on lib/course/widgets/course_detail_screen.dart
> +          }
If the course doesn't contain any lessons, we don't even display the course's name and description? I don't think that's what we want

2020-01-27 19:02 UTC, JonasWanke commented on lib/course/widgets/course_detail_screen.dart
>      return Scaffold(
Why not use a `FancyScaffold`?

2020-01-27 19:02 UTC, JonasWanke commented on lib/course/widgets/courses_screen.dart
> +              FancyAppBar(title: Text('Courses')),
Translation missing

2020-01-27 19:02 UTC, JonasWanke commented on lib/course/widgets/courses_screen.dart
> +          return CustomScrollView(
Why not use a `FancyScaffold`?

2020-01-27 19:02 UTC, JonasWanke commented on lib/course/widgets/lesson_screen.dart
>      return Scaffold(
Why not use a `FancyScaffold`?

2020-01-27 19:02 UTC, JonasWanke commented on lib/l10n/l10n.dart
> +  S get s => S.of(this);
What do you think about merging this definition into the `FancyContext` extension? Extension methods in not-yet-imported files are not being suggested by autocompletion—moving this into the `app` package could save us from manually specifying an import as `app` is already included in most files

2020-01-27 19:02 UTC, JonasWanke commented on lib/news/widgets/article_preview.dart
>          child: InkWell(
Can we use a `FancyCard` here and move it outside of `Provider`?

2020-01-27 19:02 UTC, JonasWanke commented on lib/news/widgets/news_screen.dart
> +          return CustomScrollView(
Can we use a `FancyScaffold` here?

2020-01-27 19:02 UTC, JonasWanke commented on lib/app/widgets/fancy_card.dart
> +            child: Text(title.toUpperCase(), style: context.textTheme.overline),
I think the title looks better with `mediumEmphasisColor`

2020-01-27 19:02 UTC, JonasWanke commented on lib/assignment/widgets/dashboard_card.dart
> +    return FancyCard(
We should probably use `omitHorizontalPadding`

2020-01-28 14:38 UTC, konstantin-sc commented
i like the styler and glossyness in general. only thing i feel is that the tasks don't seem to be very clickable, because there is no link indicating colour, symbol, card or whatever

2020-01-28 15:29 UTC, janrenz commented
I always feel that cards are a waste of space on small screens. This place could be used for content and content parts can still be separated. See the new mobile design form Spiegel
https://apps.apple.com/de/app/der-spiegel/id424881832

2020-01-28 15:53 UTC, konstantin-sc commented
Let's agree on making the clickabilty of assignments more visible (Sarah dindn't get it too).

Remark from Sarah: Course cards could also be optimized to the new layout. For me as PO Prio 2, if low hanging then do it, if not iterate later

@dominikbruechner could the component libray be useful here? 
@marcelgarus @JonasWanke please contact Sarah in RocketChat to meet her for feedback. And do you know our story book? https://storybook.test.schul-cloud.org/?path=/story/base-base-ui--basebutton

2020-01-28 18:46 UTC, marcelgarus commented
@janrenz I do agree that cards are a waste of screen estate for large lists of homogenous content, like news content in the Spiegel app — images that go all the way from one side of the screen to the other look way more immersive than if there was padding around them.
For groups of heterogenous content, however, I believe that cards provide a great way of grouping related information together. For example, unlike news articles where basically the only types of content are text and images, on the dashboard of the Schul-Cloud app, there are schedules with progress bars, assignments and news and much more in the future and everything has a different layout. I believe that's a great fit for cards.
This distinction between normal lists for homogenous content and cards for heterogeneous content can be seen in lots of other apps to — for example, Twitter and Instagram, which provide feeds consisting mostly of text or images, respectively, don't use cards. Google search results, LinkedIn, Facebook instead use cards to group units of content together, because their feed can contain anything from polls to text to images to website previews, etc.

So, while I'd go along with using something other than cards on the news screen or the files screen, I'd strongly argue for using cards on the dashboard. If you're still not convinced, here's a beautiful render of how active events could get highlighted in the future (we still need to fix the padding):

![image](https://user-images.githubusercontent.com/8601189/73294122-7dbc8d00-4205-11ea-8fc9-fc1deb446267.png)

@konstantin-sc About the assignments screen, we know it's very bare-bones for now — @JonasWanke is working on it, as pointed in the _known issues_ section in the PR description.

We didn't know the storybook yet, looks interesting. When we implement some more UI to talk about, we suggest having a design meeting with the UX team sometime in the following weeks.

2020-01-28 19:04 UTC, JonasWanke approved these changes

2020-01-29 05:32 UTC, janrenz commented
Also reducing the shadow could make this look lighter, but I keep this ti the UX team.. however great work!

2020-01-29 08:16 UTC, marcelgarus commented
Yup, it's definitely better than what's currently in the master (design-wise and code-wise), so I'm gonna go ahead and merge this. Future design changes are welcome of course. 😊

2020-01-29 08:17 UTC, merged

2020-01-29 10:36 UTC, konstantin-sc commented
👍 UX Team had a short review. Further discussions in #mobile or best face to face.

@janrenz the truth for the spiegel app lies in the middle: on dashboard, they group connected items on a card (e.g. articles about corona virus or best of spiegel plus). single articles are on a single card.