Support deleting and renaming files
schul-cloud/schulcloud-flutter pull request #207
Opened 2020-03-12 13:14 UTC by marcelgarus

**Merge note:** This branch is based on the `fix-caching` branch, so #160 should be merged first.

Fixes #129 
Fixes #130 

By long-tapping on files, a menu appears that lets the user select actions to take. The <kbd>Move</kbd> action does nothing for now, but <kbd>Delete</kbd> and <kbd>Rename</kbd> already work.

`FileMenu` | `RenameDialog`
---|---
![image](https://user-images.githubusercontent.com/8601189/76524614-a07bcb80-646a-11ea-984c-ade9961108a4.png) | ![image](https://user-images.githubusercontent.com/8601189/76524624-a4a7e900-646a-11ea-9d21-e3fd6c81f5f9.png)

**Note:** Although this technically counts as being able to delete and rename files, this leaves a lot to be desired. For example, after selecting an option, the user needs to navigate away from the screen and then again to the screen to cause a reload and the files to get renamed/disappear. That definitely needs to change before release. This is a more general functionality that needs to be implemented on the level of the `HiveCache` and therefore shouldn't be part of this PR.

**Todo before merging:**
- [ ] add title to `RenameDialog`
- [ ] internationalize and localize newly added Strings

2020-03-16 10:15 UTC, JonasWanke requested changes
While it works, we should improve the UI:
- Add icons for the different options in `FileMenu` and maybe order them differently (e.g. rename as a pen-icon next to the file's name)
- Add a confirm dialog before deleting a file
- Use `SecondaryButton` and `PrimaryButton` for cancel and rename actions in the dialog
- Add snack bars after both rename and delete as a confirmation for the user and maybe some loading indicator while the network request is in progress.
- Nice to have: I guess that most users intend to only change the name and not the file extension when selecting "Rename". Maybe place the cursor before the last dot or even pre-select the name (without extension)?

FYI: I created #214 in response to your note

2020-03-16 10:15 UTC, JonasWanke commented on lib/file/data.dart
> +  }
I'd guess that these network calls return the modified `File`-object. Can we store that directly?

2020-03-16 10:15 UTC, JonasWanke commented on lib/file/data.dart
> +  Future<void> delete() => services.api.delete('fileStorage/$id');
We should probably delete this file from our cache as well

2020-03-16 10:15 UTC, JonasWanke commented on lib/l10n/intl_de.arb
> +  "file_renameDialog_rename": "Umbenennen"
Please keep these sorted alphabetically (an issue on L42n was created: JonasWanke/l42n#8)

2020-03-16 10:15 UTC, JonasWanke commented on lib/l10n/intl_en.arb
> +  "file_renameDialog_rename": "Rename"
Please keep these sorted alphabetically (an issue on L42n was created: JonasWanke/l42n#8)

2020-03-16 10:15 UTC, JonasWanke commented on lib/file/widgets/file_menu.dart
> +  const FileMenu({this.file});
```suggestion
  const FileMenu(this.file) : assert(file != null);
```

2020-03-16 10:15 UTC, JonasWanke commented on lib/file/widgets/file_tile.dart
>      );
- This should probably be a static function on `FileMenu` for better reuse.
- WIth `black_hole_flutter` you can use `context.showFancyModalBottomSheet`

2020-03-16 10:15 UTC, JonasWanke commented on lib/file/widgets/file_menu.dart
> +      title: Text('Rename file'),
L10n

2020-03-16 10:15 UTC, JonasWanke commented on lib/l10n/intl_en.arb
> +  "file_renameDialog_title": "Rename file",
For titles, you can omit the suffix `_title` and just use `file_renameDialog`

2020-03-16 10:15 UTC, JonasWanke commented on lib/file/widgets/file_menu.dart
> +  }
One method uses `context.navigator` and the other one uses `context.rootNavigator`? AFAIK both refer to the same `Navigator` in this case, so probably prefer `context.navigator`?
```suggestion
  Future<void> _delete(BuildContext context) async {
    unawaited(file.delete());
    context.navigator.pop();
  }

  Future<void> _rename(BuildContext context) async {
    final newName = await showDialog<String>(
      context: context,
      useRootNavigator: true,
      builder: (_) => RenameDialog(oldName: file.name),
    );

    if (newName == null) {
      return;
    }

    unawaited(file.rename(newName));
    context.navigator.pop();
  }
```

2020-03-16 12:09 UTC, marcelgarus commented on lib/file/data.dart
> +  Future<void> delete() => services.api.delete('fileStorage/$id');
HiveCache currently doesn't support removing items… I opened an issue for that: https://github.com/schul-cloud/schulcloud-flutter/issues/216

2020-03-18 09:34 UTC, JonasWanke requested changes

2020-03-18 09:34 UTC, JonasWanke commented on lib/app/services/snack_bar.dart
> +/// A service that offers displaying app-wide SnackBars at the bottom.
```suggestion
/// A service that offers displaying app-wide [SnackBar]s at the bottom.
```

2020-03-18 09:34 UTC, JonasWanke commented on lib/app/services/snack_bar.dart
> +      showMessageShortly(String message) {
"Shortly" means soon, but I guess you mean "briefly"

2020-03-18 09:34 UTC, JonasWanke commented on lib/app/widgets/form.dart
> +    final result = showDialog<bool>(
Can you please implement this fix for `showDiscardChangesDialog` (defined above) as well?

2020-03-18 09:34 UTC, JonasWanke commented on lib/file/widgets/file_menu.dart
> +      failureMessage: "Couldn't rename to $newName",
I18n

2020-03-18 09:34 UTC, JonasWanke commented on lib/file/widgets/file_menu.dart
> +      failureMessage: "Couldn't delete ${file.name}",
I18n

2020-03-18 11:40 UTC, JonasWanke approved these changes

2020-03-18 14:01 UTC, merged