Show internal assets in content WebViews
schul-cloud/schulcloud-flutter pull request #232
Opened 2020-03-20 18:35 UTC by JonasWanke

**Fixes: #99**

**Changes**

We now show assets in lesson content that can only be accessed by signed-in users by setting a JWT-cookie.

Other notable changes:
- Prevent crash when signing out after the session already expired.
- Set minimum log level to `debug`.
- Sort lessons by their `position` field and show/hide lessons and contents based on their `hidden` field.

2020-03-21 00:00 UTC, MarcelGarus requested changes

2020-03-21 00:00 UTC, MarcelGarus commented on lib/course/widgets/lesson_screen.dart
> +        final firstContent = lesson.contents.where((c) => c.isVisible).first;
```suggestion
        final firstContent = lesson.contents.firstWhere((c) => c.isVisible);
```
Also, what if there is no content for this lesson? Throwing an error is probably not the right thing to do…

2020-03-21 00:00 UTC, MarcelGarus commented on lib/course/widgets/lesson_screen.dart
> +          for (final content in lesson.contents.where((c) => c.isVisible))
Maybe even create a getter for `visibleContents` and one on the `Course` for `visibleLessons`? Seems like the `.where(…)` call is used a lot in this code.

2020-03-21 08:56 UTC, JonasWanke commented on lib/course/widgets/lesson_screen.dart
> +          for (final content in lesson.contents.where((c) => c.isVisible))
What's the recommended way to do this for lessons within a course?
- Create a second `LazyIds<Lesson>` only containing visible lessons
- Create a getter `CacheController<List<Lesson>> get visibleLessons => lessons.controller.map(…)`

2020-03-21 09:19 UTC, JonasWanke commented on lib/course/widgets/lesson_screen.dart
> +        final firstContent = lesson.contents.where((c) => c.isVisible).first;
For now we show a button to view this lesson in the browser (and hope the user selects to open this link in a browser and not in our app).
In the future, we should improve this → #236

2020-03-21 17:07 UTC, janrenz commented
In the future we could consider this plugin: https://pub.dev/packages/webview_flutter

2020-03-21 18:38 UTC, JonasWanke commented
@janrenz We were using that plugin in the beginning but had to change to a fork because it's (white) background can't be made transparent (very noticeable in dark mode; flutter/flutter#29300). We then discovered [`flutter_inappwebview`](https://pub.dev/packages/flutter_inappwebview) which has a lot more features making both a web-based sign-in easier and viewing internal assets possible.

2020-03-21 23:13 UTC, marcelgarus commented on lib/course/widgets/lesson_screen.dart
> +          for (final content in lesson.contents.where((c) => c.isVisible))
There's currently no recommended way to do this. I would probably choose the latter one unless the API provides some more efficient way to only query visible lessons.

2020-03-21 23:17 UTC, MarcelGarus approved these changes

2020-03-22 08:21 UTC, JonasWanke commented on lib/course/widgets/lesson_screen.dart
> +          for (final content in lesson.contents.where((c) => c.isVisible))
Okay, I went with the first option. `/lessons?hidden[$ne]=true`

2020-03-22 10:05 UTC, merged