Error reporting via Sentry
schul-cloud/schulcloud-flutter pull request #244
Opened 2020-03-24 09:04 UTC by JonasWanke

**Closes: #37**

We now report errors to Sentry. Other events can also be reported using `reportEvent`.

This also adds the current `schoolId` as a query parameter to API requests for better server performance.

TODO:
- [ ] More detailed testing when I have an account ([SC-3747](https://ticketsystem.schul-cloud.org/browse/SC-3747))
- [ ] Test reporting of flutter errors in production (flutter/flutter#48972)

2020-03-24 15:27 UTC, MarcelGarus requested changes

2020-03-24 15:27 UTC, marcelgarus commented on lib/app/error_reporting.dart
> +  // have a Schrödinger's cat-situation in which we can't guarantee a permission
```suggestion
  // have a Schrödinger's cat situation in which we can't guarantee a permission
```

2020-03-24 15:27 UTC, marcelgarus commented on lib/app/services/api_network.dart
> +    assert(path[0] != '/');
```suggestion
    assert(!path.startsWith('/'));
```

2020-03-24 15:27 UTC, marcelgarus commented on lib/main.dart
> +        // get_it to keep track of initialization statuses is the simplest way.
```suggestion
        // GetIt to keep track of initialization statuses is the simplest way.
```
same as in `error_reporting.dart`

2020-03-24 15:27 UTC, marcelgarus commented on lib/settings/widgets/settings_screen.dart
> +      ]),
```suggestion
      ],),
```
\+ dartfmt

2020-03-24 23:16 UTC, MarcelGarus approved these changes

2020-03-26 08:18 UTC, JonasWanke commented
I was able to test the reported errors with Sentry; exceptions seem to all get caught. Render overflows are not yet reported, maybe we should open an issue for that? And we might want to provide a custom [`ErrorWidget`](https://api.flutter.dev/flutter/widgets/ErrorWidget-class.html) to flutter that better fits our app.

2020-03-30 11:09 UTC, MarcelGarus approved these changes

2020-03-30 11:29 UTC, merged