Filter assignments by course
schul-cloud/schulcloud-flutter pull request #257
Opened 2020-03-26 15:51 UTC by JonasWanke

**Please merge #256 first!**
**Closes: #145**

`AssignmentsScreen` can now be filtered by course. This also includes quick-filtering by tapping the course-chip on an `AssignmentCard` and parsing the query string from incoming deep links.

**Known issues:**
- I didn't get `DraggableScrollableSheet` to work inside a `ModalBottomSheet`, so there is an overflow if the SortFilter sheet is higher than the screen.

**Screenshots**

| SortFilter sheet | Active course filter  |
| :------------: | :------------: |
| ![image](https://user-images.githubusercontent.com/19330937/77667005-f92a8880-6f81-11ea-8f40-c8edddca50b1.png) | ![image](https://user-images.githubusercontent.com/19330937/77667073-09dafe80-6f82-11ea-8926-9fbee033acac.png) |

2020-03-26 21:34 UTC, MarcelGarus requested changes

2020-03-26 21:34 UTC, marcelgarus commented on lib/app/sort_filter/filtering.dart
> +                    updater(selection.whereNot((c) => c == category).toSet());
```suggestion
                    updater(selection.toSet().difference({category}));
```
or
```suggestion
                    updater(selection.toSet()..remove(category));
```

2020-03-26 21:34 UTC, marcelgarus commented on lib/assignment/widgets/assignments_screen.dart
> +typedef OnCourseClicked = void Function(Id<Course> courseId);
Hmm. It doesn't really sound like a type. What about `CourseClickedCallback`?
Also, alliterations are fun.

2020-03-27 06:15 UTC, janrenz commented
What if the list of courses gets too long?

2020-03-28 16:31 UTC, JonasWanke commented
@janrenz The intended effect would be a scrollable sheet (probably using `DraggableScrollableSheet`), but I didn't get that to work yet (i.e., it currently overflows the screen). We will still merge this PR and look into scrolling soon (#260).

2020-04-22 14:14 UTC, MarcelGarus approved these changes

2020-04-24 13:56 UTC, merged