Fix file upload
schul-cloud/schulcloud-flutter pull request #268
Opened 2020-03-30 13:17 UTC by JonasWanke

**Closes: #266**

- File upload wasn't working due to query parameters provided to our `NetworkService` via the URL i/o the `queryParameters` map. `NetworkService` now accepts parameters in either of them.
- The error wasn't logged. We now have `SnackBarService.performMultiAction` with an automatic update & failure handling.
- `AssertionError`s are automatically logged at `Level.wtf`.
- Logged messages with `level >= Level.error` are sent to Sentry in production.

2020-03-30 20:11 UTC, MarcelGarus requested changes

2020-03-30 20:11 UTC, marcelgarus commented on lib/app/error_reporting.dart
> +const _logerLevelToSentryLevel = {
```suggestion
const _loggerLevelToSentryLevel = {
```

2020-03-31 16:00 UTC, MarcelGarus approved these changes

2020-03-31 16:01 UTC, merged

2020-04-01 11:52 UTC, janrenz commented
Works well on iOS too