Show global errors
schul-cloud/schulcloud-flutter pull request #284
Opened 2020-04-19 18:24 UTC by marcelgarus

**Closes:** #259

Now, global errors are shown at the top.
For now, global errors include having no internet access and having an expired authentication token.
Also, demo accounts are now indicated by a demo tag instead of an account avatar at the top right.

**Screenshots**

![image](https://user-images.githubusercontent.com/8601189/79695706-aa1dfd80-8278-11ea-83bd-f327e6c53dd5.png)

2020-04-20 07:52 UTC, JonasWanke requested changes
Maybe we should add a more descriptive demo-banner in the `AccountDialog` so after tapping "demo" the user also gets a short explanation? (e.g., the banner text of the web-client)

2020-04-20 07:52 UTC, JonasWanke commented on lib/app/services/banner.dart
> +class Banner {
```suggestion
@immutable
class Banner {
```

2020-04-20 07:52 UTC, JonasWanke commented on lib/app/services/banner.dart
> +  const Banner(this.name);
```suggestion
  const Banner(this.name) : assert(name != null);
```

2020-04-20 07:52 UTC, JonasWanke commented on lib/app/widgets/banners.dart
> +      backgroundColor: Theme.of(context).errorColor.withOpacity(0.5),
```suggestion
      backgroundColor: context.theme.errorColor.withOpacity(0.5),
```

2020-04-20 07:52 UTC, JonasWanke commented on lib/app/widgets/account_avatar.dart
> +            snapshot.data?.avatarInitials ?? snapshot.hasError ? 'X' : '…',
`??` has a higher precedence than `e1 ? e2 : e3`: https://dart.dev/guides/language/specifications/DartLangSpec-v2.2.pdf#page=199
```suggestion
            snapshot.data?.avatarInitials ?? (snapshot.hasError ? 'X' : '…'),
```

2020-04-20 07:52 UTC, JonasWanke commented on lib/main.dart
> +            user?.roleIds?.contains(Id<Role>('0000d186816abba584714d02')) ??
This is the role ID of a demo student. We also need that of a demo teacher: 0000d186816abba584714d03
Source: https://github.com/schul-cloud/schulcloud-server/blob/a2e15cb617916589cabbe18c0deea8499ed61080/backup/setup/roles.json#L301-L342

Or (even better): Check transitively included roles for `demo` (0000d186816abba584714d00): https://github.com/schul-cloud/schulcloud-server/blob/a2e15cb617916589cabbe18c0deea8499ed61080/backup/setup/roles.json#L248-L278

2020-04-20 07:52 UTC, JonasWanke commented on lib/l10n/intl_en.arb
> +  "app_demo": "demo",
```suggestion
  "app_demo": "Demo",
```

2020-04-20 07:52 UTC, JonasWanke commented on lib/app/widgets/banners.dart
> +        padding: EdgeInsets.all(8),
I'd prefer a horizontal padding of 16 so it matches our globally used horizontal padding (i.e., that of the AppBar title and list items).
(Also applies to the `TokenExpiredBanner` below.)

2020-04-20 07:52 UTC, JonasWanke commented on lib/app/widgets/banners.dart
> +class TokenExpiredBanner extends StatelessWidget {
We might want to include a sign-out-icon here directly so the user doesn't have to search for it

2020-04-20 10:15 UTC, marcelgarus commented
There's now a sign out button in the `TokenExpiredBanner` and a demo explanation in the `AccountDialog`:

sign out button | demo explanation
---|---
![image](https://user-images.githubusercontent.com/8601189/79738348-eabf5a80-82fc-11ea-9077-68bdf469c8f0.png) | ![image](https://user-images.githubusercontent.com/8601189/79740305-be590d80-82ff-11ea-960d-80958f619f92.png)

2020-04-20 13:54 UTC, JonasWanke requested changes

2020-04-20 13:54 UTC, JonasWanke commented on lib/l10n/intl_en.arb
> +  "app_demo_explanation": "This is a demo account. You may not be able to perform certain actions, like uploading files.",
Fun fact: uploading files is the one write-operation you _can_ perform as a demo user: https://github.com/schul-cloud/schulcloud-server/blob/a2e15cb617916589cabbe18c0deea8499ed61080/backup/setup/roles.json#L267

Maybe keep it general like "This is a demo account. All actions that create or change data are deactivated and not visible." (translated from the web-client) and ignore that exception?

(This also applies to the German translation.)

2020-04-20 13:54 UTC, JonasWanke commented on lib/app/widgets/banners.dart
> +                color: context.theme.isDark ? Colors.white : Colors.black,
black_hole_flutter to the rescue!
```suggestion
                color: context.theme.contrastColor,
```

2020-04-21 13:07 UTC, JonasWanke approved these changes

2020-04-22 10:40 UTC, merged