Migrate assignment module
schul-cloud/schulcloud-flutter pull request #301
Opened 2020-05-22 06:52 UTC by JonasWanke

2020-05-24 07:13 UTC, MarcelGarus requested changes

2020-05-24 07:13 UTC, MarcelGarus commented on lib/assignment/pages/assignment_detail_page/page.dart
> +                initialIndex: math.min(initialTabIndex ?? 0, tabs.length - 1),
A few lines above we check if `initialTabIndex < 0`. Can't we directly after we do the `indexOf` just `clamp` it? Like `initialTabIndex = initialTabIndex.clamp(0, tabs.length - 1)`

2020-06-26 14:34 UTC, JonasWanke commented on lib/assignment/pages/assignment_detail_page/page.dart
> +                initialIndex: math.min(initialTabIndex ?? 0, tabs.length - 1),
Moved to #317

2020-06-26 14:35 UTC, MarcelGarus approved these changes

2020-06-26 16:20 UTC, merged