Migrate news module
schul-cloud/schulcloud-flutter pull request #338
Opened 2020-08-16 16:12 UTC by JonasWanke

2020-08-22 18:07 UTC, MarcelGarus requested changes

2020-08-22 18:07 UTC, MarcelGarus commented on lib/app/utils.dart
> +    _str.write(node.data);
Should we add spaces?
Something like this would look bad:
```html
<p>Some</p><p>text</p>
```

2020-08-26 07:54 UTC, JonasWanke commented on lib/app/utils.dart
> +    _str.write(node.data);
Whitespace should be better now.

2020-08-27 11:19 UTC, marcelgarus approved these changes

2020-08-28 17:17 UTC, merged