Add splash screen
schul-cloud/schulcloud-flutter pull request #353
Opened 2020-10-13 11:54 UTC by marcelgarus

This PR adds a proper splash screen to the Android app.

Before, the init screens were as follows:

- A white screen (native)
- A white screen with a circular loading indicator (Flutter)
- The actual content (Flutter)

Now, the screens are:

- An screen with an adaptive background color and the logo (native)
- The actual content (Flutter)

That's a better startup experience.

![splash screen in dark mode](https://user-images.githubusercontent.com/8601189/95857136-74eff500-0d5b-11eb-9ba2-eae0eb60581d.png)

2020-10-14 11:49 UTC, JonasWanke requested changes

2020-10-14 11:49 UTC, JonasWanke commented on android/app/src/main/res/drawable/launch_background.xml
> +    <item android:drawable="@drawable/ic_launcher_foreground" android:gravity="center" />
This doesn't appear to be themed but is always white using the SC flavor.

2020-10-15 12:05 UTC, marcelgarus commented
I adjusted the splash screen to show the actual app icon in the center, that looks nice in both light and dark mode.
Have a look:

| default theme light | default theme dark | NBC light |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/8601189/96120520-ead89580-0eee-11eb-856e-4d0e3e56da53.png) | ![image](https://user-images.githubusercontent.com/8601189/96120458-d1cfe480-0eee-11eb-9f69-c834509be6f9.png) | ![image](https://user-images.githubusercontent.com/8601189/96120713-3d19b680-0eef-11eb-821d-eaa36082396a.png) |

2020-10-15 12:08 UTC, JonasWanke approved these changes

2020-12-15 20:49 UTC, Th3Ph4nt0m commented
Is it on purpose that these changes have not yet been merged?

2020-12-18 09:24 UTC, merged

2020-12-18 09:25 UTC, marcelgarus commented
Nope, thanks for noticing