Architecture rework
schul-cloud/schulcloud-flutter pull request #48
Opened 2019-09-14 19:40 UTC by marcelgarus

Contrary to the name of this branch, the logout is not implemented yet, sorry about that. 👀

**So, what exactly is new?**
* The core module is gone! Per definition, it only contained code that's not app-specific. This has been outsourced into public dart packages named [`repository`](https://pub.dev/packages/repository), [`repository_hive`](https://pub.dev/packages/repository_hive) and [`repository_shared_preferences`](https://pub.dev/packages/repository_shared_preferences).
* Speaking of `repository_hive`, we now use [`hive`](https://pub.dev/packages/hive) for storing data locally. This is not used extensively throughout the app yet (only in the news and app module, if I remember correctly), but it's very easy to integrate custom types.
* The file structure inside the modules also changed a little bit—there's no `data` directory anymore, rather there's just a `data.dart` file. Extensive research showed that we only used about 1-3 data classes in the modules anyway, so merging those into one file leaves us with less boilerplate.
* The services got fancier! There's no more `ApiService` anymore, rather the module-specific logic went into the modules themselves. So, no more wrapper repository just to call `api.listNews()`, it happens right there. Also, a new utility repository `CollectionDownloader` is now in the `app/utils.dart`. You just need to implement one simple method for downloading all the items—no more manual maintaining of a `_downloader` and checking `if (_items == null) await _downloader;` in the fetch methods!
* The service initialization also got updated. The `SplashScreen` now waits for all services to be initialized and only then redirects to the actual app. Very fancy!
* The imports got a lot cleaner! There were some interdependencies between modules, which isn't necessarily bad, but made it harder to reason about the effect of changes when working on a module. Now, anything used outside of a module is exported in the `<module>/<module>.dart`, so other packages only need to import the top-level module file, i.e. `app/app.dart` instead of `app/utils.dart`, `app/widgets.dart` etc.

**Known problems?**
* The files screen no longer contains the courses. The reason is there's a strong linkage between the `courses` and the `files` modules—because the file screen also displays all the courses, it has logic quite similar to the course screen. Perhaps, we can fix this by implementing a new `CourseService` of sorts, that allows for downloading the courses and is used among the modules.

2019-09-17 12:48 UTC, ctiedt requested changes
It appears that you included a number of automatically generated files (in particular the `.dart_tool` and `.idea` directories) that should normally be excluded  through your `.gitignore`.

2019-09-17 12:48 UTC, ctiedt commented on lib/app/widgets/menu.dart
> +    Navigator.of(context).pushReplacementNamed(Routes.login.toString());
`Routes.login.toString()` should be `Routes.login.name` as the former will confuse the navigator.

2019-09-17 12:48 UTC, ctiedt commented on lib/courses/bloc.dart
> +      source: LessonDownloader(network: network, courseId: courseId),
As this reloads the lessons every time it is called, the cache seems superfluous here.

2019-09-17 12:48 UTC, ctiedt commented on lib/app/services/me.dart
> +  // A JWT token exists of a header, body and claim (signature), all separated
"exists" should be changed to "consists"

2019-09-17 12:48 UTC, ctiedt commented on lib/courses/bloc.dart
> +    print('Courses done');
This debug print statement should be removed.

2019-09-17 12:48 UTC, ctiedt commented on lib/files/widgets/files_screen.dart
> +          child: Scaffold(
As the `FilesView` has its own `Scaffold` , it should not be wrapped in one here.

2019-09-17 12:48 UTC, ctiedt commented on ios/Flutter/flutter_export_environment.sh
> +# This is a generated file; do not edit or check into version control.
As the file says, it should not be included in the git repository.

2019-09-17 12:48 UTC, ctiedt commented on .dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/asset_graph.json
> +{"version":22,"dart_version":"2.5.0-dev.4.0.flutter-be66176534 (Thu Sep 5 15:05:53 2019 +0000) on \"windows_x64\"","nodes":[[5,0,[],[],null,[]],[5,1,[],[],null,[]],[5,2,[],[],null,[]],[0,3,[],[],null
This appears to be an automatically generated file and should not be included in any commits.

2019-09-17 12:48 UTC, ctiedt commented on .dart_tool/build/entrypoint/build.dart
> +// ignore_for_file: directives_ordering
This appears to be an automatically generated/build related file and should not be included in any commits.

2019-09-18 11:01 UTC, marcelgarus commented on lib/app/widgets/menu.dart
> +    Navigator.of(context).pushReplacementNamed(Routes.login.toString());
Because the logout doesn't work anyway, I commented it out for now.

2019-09-18 19:08 UTC, ctiedt approved these changes

2019-09-18 20:03 UTC, merged